package ex08.example2;

public class TryEx02 {
    public static void main(String[] args) {
        throw new RuntimeException("오류 강제 발생"); // 강제로 오류를 발생 시키는 것
    }
}
